Math Magicians: Components
yigitm/math-magicians pull request #2
Opened 2022-01-04 22:58 UTC by yigitm

Below features/actions are done;

-Deleted all the boilerplate from CRA (text, images, styles)
-Created a directory called components
-Created a React component for UI
-Used class-based component
-Tested in browser

Thank you for your time.

2022-01-04 23:22 UTC, omar-labana requested changes
Hi @yigitm, 

Excellent work so far! 👌
You have implemented all the requirements correctly. Furthermore, you have made an excellent job sticking to the calculator styling. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-04 23:22 UTC, omar-labana commented on public/index.html
> +  <body></body>
- [ ] By convention, using the `root` div element is the normal way to approach react apps, I'd suggest sticking to the conventions as much as possible.
![image](https://user-images.githubusercontent.com/33767951/148136633-ba9495d6-b7e9-4ded-9f44-74a0f69e96fa.png)

2022-01-04 23:22 UTC, omar-labana commented on src/components/Calculator.js
> +const UI = (
- [ ] Kindly, rename the components so it matches the module/component name since you're using es6 default exports.
-> `const Calculator` instead of `const UI`

2022-01-04 23:35 UTC, yigitm commented on public/index.html
> +  <body></body>
Thank you. The render element is changed to 'root'.

2022-01-04 23:36 UTC, yigitm commented on src/components/Calculator.js
> +const UI = (
Thank you. The component is changed to 'Calculator'.

2022-01-05 00:08 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @yigitm, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 00:10 UTC, merged